### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by DarkoniusXNG** [OpenAngelArena/oaa#2987]
- [ ] Fix corner camp abuse with small camps.
- [ ] Change Midas Spark (current ideas: increase XP gained on creep kill by 10%; increase XP gained with bounty runes)
- [ ] Bounty Runes check code if gold reward is correct. Hud message shows 40 gold even after 40 minutes.
- [ ] Fix Alchemist passive not working with Bounty Runes.
- [ ] Add abilities to Wanderer Boss.
- [ ] Make Wanderer Bosses more distinguishable. Bat/Owl/Manta.
- [ ] Dragon Knight ultimate and aghanim scepter upgrade rewrite. Level 4 Black Dragon - magic resistance and flying movement. Level 5 White Dragon - HP regen/Lifesteal/Heal reduction. Aghs - permanent Dragon Form and improves other Dragon Form abilities.
- [ ] Greater Tranquil Boots - add Tree-walking, add sound and particles for the active.
- [ ] Neutral item Book of the Dead rewrite - Necronomicon Warrior lvl 3, Necronomicon Archer lvl 3 + 2 new units unique for OAA.
- [ ] Add 2 more new neutral items to last tier of neutral items.
- [ ] Nature's Prophet ultimate rework - Point-AoE ability has an effect only in a selected radius. Deals double or triple dmg to creeps. Ignores bosses.
- [ ] Fix bugs with Monkey King ultimate and talents.
- [ ] Pull Staff rework/refactor - fix bugs (infinite particle stacking) and ''features'' related to Chronosphere and Black Hole.
- [ ] Fix Sven boss, Slime boss etc. showing particles in affected areas when their ability finished instead of before.
- [ ] Add new ability to Bear boss - Overpower: AoE Earthshock + bonus 400 attack speed for a few seconds, it shows an indicator above the boss and around the boss when its about to be cast.
- [ ] Precache Slime boss particles to reduce lag.
- [ ] Optimise tier 3 bosses as much as you can, because the code from siltbreaker is mostly bad.
- [ ] Add Magma Boss
- [ ] Change Lucience hp regen aura from heals to actual hp regen.
- [ ] New Item Ninja Gear
- [ ] New Item A Sacred Skull
- [ ] Add Final Boss
